# Generated by Django 4.2.11 on 2025-07-11 06:01

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survey Response', 'verbose_name_plural': 'Survey Responses'},
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='correctly_answered',
            field=models.TextField(blank=True, null=True, validators=[myapp.models.validate_comma_separated_ints]),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['score'], name='myapp_surve_score_61ed09_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['passed'], name='myapp_surve_passed_f74c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['created_at'], name='myapp_surve_created_b6a8ef_idx'),
        ),
    ]
