# Generated by Django 4.2.11 on 2025-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_surveyresponse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
