# Generated by Django 4.2.11 on 2025-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_surveyresponse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['gender'], name='myapp_surve_gender_92f685_idx'),
        ),
    ]
