# Generated by Django 4.2.11 on 2025-07-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_surveyresponse_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='myapp_surve_modifie_9e6cef_idx',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='modified_at',
        ),
    ]
