# Generated by Django 4.2.11 on 2025-07-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_surveyresponse_myapp_surve_modifie_9e6cef_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='myapp_surve_gender_92f685_idx',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='player_name',
        ),
    ]
