# Generated by Django 4.2.11 on 2025-07-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_remove_surveyresponse_myapp_surve_gender_92f685_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['gender'], name='myapp_surve_gender_92f685_idx'),
        ),
    ]
