# Generated by Django 4.2.11 on 2025-07-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_surveyresponse_gender_surveyresponse_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
    ]
